name: aultra_paints_mobile
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


# version: 1.0.1+3
version: 11.0.0+24

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  encrypt: ^5.0.1
  shared_preferences: ^2.1.1 
  intl: ^0.17.0
  image_picker: ^0.8.7+5
  dio: ^5.1.2
  url_launcher: ^6.1.12
  loading_animation_widget: ^1.2.0+4
  qr_mobile_vision: ^5.0.2
  provider: ^6.0.5
  flutter_easyloading: ^3.0.5
  font_awesome_flutter: ^10.7.0 
  permission_handler: ^10.3.0
  internet_connection_checker: ^1.0.0+1 

 
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8 

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
  - assets/certificate/AultraPaints_b20bd50c61d9d911.crt_1
  - assets/certificate/AultraPaints_b20bd50c61d9d911.crt
  - assets/certificate/AultraPaints_b20bd50c61d9d911.pem
  - assets/certificate/AultraPaints_gd_bundle-g2-g1.crt
  - assets/
  - assets/images/
  #  - assets/certificate/STAR_mlldev_com.crt
  #  - assets/certificate/STAR_mllqa_com.crt
    

#
#  fonts:
#    - family: Helvetica
#      fonts:
#        - asset: assets/font/Helvetica.ttf
#
#    - family: HelveticaMedium
#      fonts:
#        - asset: assets/font/HelveticaMedium.ttf
#
#    - family: HelveticaBold
#      fonts:
#        - asset: assets/font/HelveticaBold.ttf
#
#    - family: GeoramaSemiExpandedBold
#      fonts:
#        - asset: assets/font/georama_semiexpanded_bold.ttf
#
#    - family: GeoramaSemiExpandedExtraBold
#      fonts:
#        - asset: assets/font/georama_semiexpanded_extrabold.ttf
#
#    - family: GeoramaSemiExpandedLight
#      fonts:
#        - asset: assets/font/georama_semiexpanded_light.ttf
#
#    - family: GeoramaSemiExpandedMediumItalic
#      fonts:
#        - asset: assets/font/georama_semiexpanded_medium_italic.ttf
#
#    - family: GeoramaSemiExpandedMedium
#      fonts:
#        - asset: assets/font/georama_semiexpanded_medium.ttf
#
#    - family: GeoramaSemiExpandedRegular
#      fonts:
#        - asset: assets/font/georama_semiexpanded_regular.ttf
#
#    - family: GeoramaSemiExpandedSemiBold
#      fonts:
#        - asset: assets/font/georama_semiexpanded_semibold.ttf

 

  


